# Generated by Django 5.1.1 on 2024-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
